### ISSUE TITLE
Issues building image w/ M1 chips

### ISSUE THREAD

**Issue by ldbro0** [billdenney/Pharmacometrics-Docker#10]
Hi Bill, 

I'm trying to build this image on my mac-book, it has a M1 Max chip, I seem to be having issues with fortran compilation step.  Are there any modifications needed?

**Comment by billdenney** [comment]
I don't have a Mac that I can test this with.  I would have guessed that it should just work, but I know that there is some degree of architecture detection during the installation process and maybe having the mix of a Linux OS and a Mac processor is causing issues.  Could you share the issue with on NM Users (or directly with Bob Bauer) and see if they have insight?

**Comment by billdenney** [comment]
To be clearer, the architecture detection happens within the NONMEM installer, not on the Docker side.

**Comment by ldbro0** [comment]
Agreed, I thought it would just "work" I suspect the newer apple silicon is causes some dependency issues.  I'll see if nmusers have any thoughts.

**Comment by billdenney** [comment]
Did you find a solution?

**Comment by ldbro0** [comment]
Not yet, if I find a solution I'll post it here

Also here's the error if you're interested 
[error.txt](https://github.com/billdenney/Pharmacometrics-Docker/files/11521381/error.txt)
