### ISSUE TITLE
NONMEM 7.5

### ISSUE THREAD

**Issue by RichardHooijmaijers** [billdenney/Pharmacometrics-Docker#3]
I did some testing with NONMEM 7.5 on docker. Maybe it is nice to add this NONMEM version here as well.
 
There might be some things to take into account however; Initially the installation failed because it searches for "libgfortran.so.3". This is present when installing libgfortran3 (`apt-get install libgfortran3`). Unfortunately, this cannot be installed on ubuntu 20.04 and had to revert back to 18.04. In the end I got it working, so if you want to implement it an need some help with it, just let me know!

**Comment by billdenney** [comment]
This is something that I hope to look at over the next few weeks.  I was hoping to test NM 7.5 and Ubuntu 20.04.  If you have made progress, I'd definitely appreciate any pointers or pull requests.

**Comment by RichardHooijmaijers** [comment]
Just tested the updated install files for NM7.5 provided by Bob on Ubuntu 20.04 with the latest gfortran version. I can confirm that the problem no longer exist! I guess that this PR (#4) is therefore also no longer applicable.

**Comment by billdenney** [comment]
Thanks for checking it.
