### ISSUE TITLE
PsN 5.3.0 challenges

### ISSUE THREAD

**Issue by RichardHooijmaijers** [billdenney/Pharmacometrics-Docker#5]
I tried to install the latest PsN version within docker, and when starting with your original code it failed. The reason is that PsN uses a new perl lib `MouseX::Params::Validate`. The problem I faced was that I was not able to install this library using `apt-get install`.  For now I used a slightly different approach that works for me, maybe you can have a look at this example and see if it can be implemented or if there is maybe a better/easier way to do it.

I used cpanminus to install all perl packages, the advantage here is that for the installation of packages you can almost directly follow the PsN installation pages. To do so we can add something like this to apt-get install:

```
RUN apt-get install --yes --no-install-recommends cpanminus
```  

Then to install the perl packages we can use something like:

```
RUN cpanm Math::Random \
 && cpanm MouseX::Params::Validate \
 && cpanm Archive::Zip
```

**Comment by billdenney** [comment]
Thanks for figuring it out.  It seems like you've solved it.  Can you please make a PR?

**Comment by RichardHooijmaijers** [comment]
Done :) #6
