### ISSUE TITLE
Installation fails under Windows 11 Pro

### ISSUE THREAD

**Issue by kestrel99** [billdenney/Pharmacometrics-Docker#9]
Everything works perfectly under Windows 11 Pro, but the completed image fails to run - error message "Error response from daemon: configured logging driver does not support reading". Not sure how to proceed.

**Comment by billdenney** [comment]
A brief search for the error suggests that it may be a docker setup issue (https://forums.docker.com/t/configured-logging-driver-does-not-support-reading/33042 and https://stackoverflow.com/questions/52326304/configured-logging-driver-does-not-support-reading-docker).  Can you run other docker containers?
